[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "binpack-loader"
version = "0.1.0"
description = "PyO3 bindings for the sfbinpack loader"
requires-python = ">=3.8"
authors = [{ name = "lewis-carson" }]
